.TH Licenser 1 "Sat Jun 15, 2024" "Version 1.0.0" "Apache Software Productions (ASP)"
.SH NAME
Licenser \- A fast, simple command line license text generator inspired by and based off of https://github.com/nishanths/license.

.SH SYNOPSIS
.B Licenser
[-help] [License document] [Filename]

.SH DESCRIPTION
Licenser is a Command line tool that has a big libray of license documents that you can automaticly copy to a LICENSE file. You can also add more license documents easily.

.SH OPTIONS
.TP
.B \-help
this will present this Manpage.

.SH EXAMPLES
.PP
.B ./Licenser \gpl-2.0 example.txt
.PP
This will copy the text in gpl-2.0.tmpl to example.txt.

.SH AUTHOR
.I AeternusDio - https://github.com/AeternusDio
.br
.I Apache Software Productions (ASP)

.SH COPYRIGHT
Copyright (C) 2024 Apache Software Productions (ASP)

.SH LICENSE
Licenser is dual licensed under the Apache Software Productions (ASP) License Version 2 & The MIT license.

.SH REPORTING BUGS
Report bugs to: https://github.com/Apache-Software-Productions/Licenser/issues
