.TH Licenser 1 "Sat Jun 15, 2024" "Version 1.0.0" "Apache Software Productions (ASP)"
.SH NAME
Licenser \- A fast, simple command line license text generator inspired by and based off of https://github.com/nishanths/license.

.SH SYNOPSIS
.B Licenser
[-help] [License document] [Filename]

.SH DESCRIPTION
Licenser is a Command line tool that has a big libray of license documents that you can automaticly copy to a LICENSE file. You can also add more license documents easily.

.SH OPTIONS
.TP
.B \-help
this will present this Manpage.

.SH EXAMPLES
.PP
.B ./Licenser \gpl-2.0 example.txt
.PP
This will copy the text in gpl-2.0.tmpl to example.txt.

.SH ALL CURRENT LICENSE DOCUMENTS NAMES
.PP
.IP \[bu] 2
ecl-2.0
.IP \[bu] 2
eupl-1.2
.IP \[bu] 2
lgpl-3.0
.IP \[bu] 2
wtfpl
.IP \[bu] 2
mulanpsl-2.0
.IP \[bu] 2
mpl-2.0
.IP \[bu] 2
ms-rl
.IP \[bu] 2
lgpl-2.1
.IP \[bu] 2
cc-by-4.0
.IP \[bu] 2
epl-2.0
.IP \[bu] 2
bsd-0-clause
.IP \[bu] 2
mit-0
.IP \[bu] 2
free-art-1.3
.IP \[bu] 2
osl-3.0
.IP \[bu] 2
bsd-3-clause
.IP \[bu] 2
afl-3.0
.IP \[bu] 2
agpl-3.0
.IP \[bu] 2
cc-by-sa-4.0
.IP \[bu] 2
zlib
.IP \[bu] 2
apache-2.0
.IP \[bu] 2
al-2.0
.IP \[bu] 2
mit
.IP \[bu] 2
isc
.IP \[bu] 2
cc0-1.0
.IP \[bu] 2
lppl
.IP \[bu] 2
unlicense
.IP \[bu] 2
bsd-4-clause
.IP \[bu] 2
ms-pl
.IP \[bu] 2
bsd-2-clause
.IP \[bu] 2
ofl-1.1
.IP \[bu] 2
odbl-1.0
.IP \[bu] 2
gpl-2.0
.IP \[bu] 2
gpl-3.0
.IP \[bu] 2
asp-1.0
.IP \[bu] 2
asp-2.0


.SH AUTHOR
.I AeternusDio - https://github.com/AeternusDio
.br
.I Apache Software Productions (ASP)

.SH COPYRIGHT
Copyright (C) 2024 Apache Software Productions (ASP)

.SH LICENSE
Licenser is dual licensed under the Apache Software Productions (ASP) License Version 2 & The MIT license.

.SH REPORTING BUGS
Report bugs to: https://github.com/Apache-Software-Productions/Licenser/issues
